baseURL = 'https://example.org/'
languageCode = 'fr-fr'
title = 'Paroisse Saint-François Xavier'
theme = ["toha"]
defaultContentLanguage = "fr"
publishDir = "docs"

[params]
    description = "Paroisse Saint-François Xavier de Navarrenx et Sauveterre"
    [params.logo]
        favicon = "images/logo.png"

[languages]
    [languages.fr]
       languageCode = "fr-fr"
       languageDirection = "ltr"
       languageName = "French"
       weight = 1

[markup]
    [markup.goldmark]
         [markup.goldmark.renderer]
             unsafe = true

[menus]
    [[menus.main]]
        name = "La paroisse"
        pageRef = "/paroisse"
        weight = 10
    [[menus.main]]
        name = "La vie communautaire"
        pageRef = "/la-vie-communautaire"
        weight = 20
    [[menus.main]]
        name = "Contact"
        pageRef = "/contact"
        weight = 30
    [[menus.main]]
        name = "Don"
        pageRef = "/don"
        weight = 40